import { Station } from "./types";

export const BRAZIL_POPULAR_STATIONS: Station[] = [
  // --- SÃO PAULO ---
  {
    changeuuid: "br-sp-alpha",
    stationuuid: "br-sp-alpha",
    name: "Alpha FM 101.7",
    url: "https://26683.live.streamtheworld.com/RADIO_ALPHAFMAAC.aac",
    url_resolved: "https://26683.live.streamtheworld.com/RADIO_ALPHAFMAAC.aac",
    homepage: "https://alphapm.com.br",
    favicon: "https://alphapm.com.br/favicon.ico",
    tags: "mpb,pop,adult contemporary,são paulo,hits",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 4950,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-antena1",
    stationuuid: "br-sp-antena1",
    name: "Antena 1 94.7 FM",
    url: "https://antenaone.crossradio.com.br/stream/1",
    url_resolved: "https://antenaone.crossradio.com.br/stream/1",
    homepage: "https://www.antena1.com.br",
    favicon: "https://www.antena1.com.br/favicon.ico",
    tags: "pop,classic pop,adult contemporary,hits,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 4620,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-jovempan",
    stationuuid: "br-sp-jovempan",
    name: "Jovem Pan FM 100.9",
    url: "https://stream.zeno.fm/g6e5t8yev0hvv",
    url_resolved: "https://stream.zeno.fm/g6e5t8yev0hvv",
    homepage: "https://jovempan.com.br",
    favicon: "https://jovempan.com.br/favicon.ico",
    tags: "pop,dance,hits,jovem pan,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 4180,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-radiorock",
    stationuuid: "br-sp-radiorock",
    name: "89 FM A Rádio Rock",
    url: "https://23033.live.streamtheworld.com/RADIO_89FMAAC.aac",
    url_resolved: "https://23033.live.streamtheworld.com/RADIO_89FMAAC.aac",
    homepage: "https://www.radiorock.com.br",
    favicon: "https://www.radiorock.com.br/favicon.ico",
    tags: "rock,classic rock,alternative,indie,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3890,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-kissfm",
    stationuuid: "br-sp-kissfm",
    name: "Kiss FM 92.5",
    url: "https://ssl.redemidia.net:8000/kissfm",
    url_resolved: "https://ssl.redemidia.net:8000/kissfm",
    homepage: "https://kissfm.com.br",
    favicon: "https://kissfm.com.br/favicon.ico",
    tags: "classic rock,hard rock,heavy metal,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3510,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-metropolitana",
    stationuuid: "br-sp-metropolitana",
    name: "Metropolitana FM 98.5",
    url: "https://icecast.metropolitanafm.com.br/stream",
    url_resolved: "https://icecast.metropolitanafm.com.br/stream",
    homepage: "https://metropolitanafm.com.br",
    favicon: "https://metropolitanafm.com.br/favicon.ico",
    tags: "pop,funk,dance,hits,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3420,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-energia97",
    stationuuid: "br-sp-energia97",
    name: "Energia 97 FM",
    url: "https://streaming.radios.com.br:8003/energia97",
    url_resolved: "https://streaming.radios.com.br:8003/energia97",
    homepage: "https://energia97.com.br",
    favicon: "https://energia97.com.br/favicon.ico",
    tags: "electronic,dance,house,stadium97,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3290,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-transamerica",
    stationuuid: "br-sp-transamerica",
    name: "Rádio Transamérica 100.1 FM",
    url: "https://transamericasp.crossradio.com.br/stream/1",
    url_resolved: "https://transamericasp.crossradio.com.br/stream/1",
    homepage: "https://www.radiotransamerica.com.br",
    favicon: "https://www.radiotransamerica.com.br/favicon.ico",
    tags: "rock,pop,esportes,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3110,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-bandnews",
    stationuuid: "br-sp-bandnews",
    name: "BandNews FM 96.9 SP",
    url: "https://evpp.mm.uol.com.br/live/bandnewsfm_sp/playlist.m3u8",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/BANDNEWSFMAAC.aac",
    homepage: "https://bandnewsfm.band.uol.com.br",
    favicon: "https://bandnewsfm.band.uol.com.br/favicon.ico",
    tags: "notícias,news,talk,jornalismo,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 2980,
    codec: "AAC",
    bitrate: 96,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-bandeirantes",
    stationuuid: "br-sp-bandeirantes",
    name: "Rádio Bandeirantes 90.9 FM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/BANDEIRANTESAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/BANDEIRANTESAAC.aac",
    homepage: "https://band.uol.com.br/radio-bandeirantes",
    favicon: "https://band.uol.com.br/favicon.ico",
    tags: "notícias,esportes,futebol,jornalismo,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 2850,
    codec: "AAC",
    bitrate: 96,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-cultura",
    stationuuid: "br-sp-cultura",
    name: "Rádio Cultura FM 103.3",
    url: "https://stream.zeno.fm/g4f4v6y2vahvv",
    url_resolved: "https://stream.zeno.fm/g4f4v6y2vahvv",
    homepage: "https://culturafm.cmais.com.br",
    favicon: "",
    tags: "clássica,erudita,jazz,cultura,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 2430,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-culturabrasil",
    stationuuid: "br-sp-culturabrasil",
    name: "Rádio Cultura Brasil 1200 AM",
    url: "https://stream.zeno.fm/g4f4v6y2vahvv",
    url_resolved: "https://stream.zeno.fm/g4f4v6y2vahvv",
    homepage: "https://culturabrasil.cmais.com.br",
    favicon: "",
    tags: "mpb,samba,choro,brasilidades,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 2190,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-novabrasil",
    stationuuid: "br-sp-novabrasil",
    name: "Novabrasil FM 89.7",
    url: "https://stream.zeno.fm/54pkvtqxv0hvv",
    url_resolved: "https://stream.zeno.fm/54pkvtqxv0hvv",
    homepage: "https://novabrasilfm.com.br",
    favicon: "https://novabrasilfm.com.br/favicon.ico",
    tags: "mpb moderna,bossa nova,pop brasileiro,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 2750,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
  {
    changeuuid: "br-sp-nativa",
    stationuuid: "br-sp-nativa",
    name: "Nativa FM 95.3",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/NATIVAFMAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/NATIVAFMAAC.aac",
    homepage: "https://radios.band.uol.com.br/nativa",
    favicon: "",
    tags: "sertanejo,romântico,popular,são paulo",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 2310,
    codec: "AAC",
    bitrate: 96,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },

  // --- RIO DE JANEIRO ---
  {
    changeuuid: "br-rj-jbfm",
    stationuuid: "br-rj-jbfm",
    name: "JB FM 99.9 Rio",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
    homepage: "https://jb.fm",
    favicon: "https://jb.fm/favicon.ico",
    tags: "mpb,pop,adult contemporary,rio de janeiro",
    country: "Brazil",
    countrycode: "BR",
    state: "Rio de Janeiro",
    language: "portuguese",
    votes: 4320,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -22.9068,
    geo_long: -43.1729,
  },
  {
    changeuuid: "br-rj-radiocidade",
    stationuuid: "br-rj-radiocidade",
    name: "Rádio Cidade 102.7 RJ",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOCIDADEAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOCIDADEAAC.aac",
    homepage: "https://radiocidade.fm",
    favicon: "https://radiocidade.fm/favicon.ico",
    tags: "rock,classic rock,rio de janeiro",
    country: "Brazil",
    countrycode: "BR",
    state: "Rio de Janeiro",
    language: "portuguese",
    votes: 3910,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -22.9068,
    geo_long: -43.1729,
  },
  {
    changeuuid: "br-rj-tupi",
    stationuuid: "br-rj-tupi",
    name: "Super Rádio Tupi 96.5 FM",
    url: "https://ssl.painelcast.com:7104/stream",
    url_resolved: "https://ssl.painelcast.com:7104/stream",
    homepage: "https://www.tupi.fm",
    favicon: "https://www.tupi.fm/favicon.ico",
    tags: "notícias,futebol,variedades,rio de janeiro",
    country: "Brazil",
    countrycode: "BR",
    state: "Rio de Janeiro",
    language: "portuguese",
    votes: 3670,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -22.9068,
    geo_long: -43.1729,
  },
  {
    changeuuid: "br-rj-bossajazz",
    stationuuid: "br-rj-bossajazz",
    name: "Bossa Jazz Brasil",
    url: "https://ssl.painelcast.com:6956/stream",
    url_resolved: "https://ssl.painelcast.com:6956/stream",
    homepage: "https://bossajazzbrasil.com",
    favicon: "",
    tags: "bossa nova,samba jazz,mpb,rio de janeiro",
    country: "Brazil",
    countrycode: "BR",
    state: "Rio de Janeiro",
    language: "portuguese",
    votes: 2950,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -22.9068,
    geo_long: -43.1729,
  },

  // --- MINAS GERAIS (BELO HORIZONTE) ---
  {
    changeuuid: "br-mg-itatiaia",
    stationuuid: "br-mg-itatiaia",
    name: "Rádio Itatiaia 95.7 FM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/ITATIAIAAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/ITATIAIAAAC.aac",
    homepage: "https://itatiaia.com.br",
    favicon: "https://itatiaia.com.br/favicon.ico",
    tags: "notícias,esportes,futebol,minas gerais,belo horizonte",
    country: "Brazil",
    countrycode: "BR",
    state: "Minas Gerais",
    language: "portuguese",
    votes: 3820,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -19.9167,
    geo_long: -43.9345,
  },
  {
    changeuuid: "br-mg-alvorada",
    stationuuid: "br-mg-alvorada",
    name: "Alvorada FM 94.9 BH",
    url: "https://streaming.radios.com.br:8003/alvoradafm",
    url_resolved: "https://streaming.radios.com.br:8003/alvoradafm",
    homepage: "https://alvoradafm.com.br",
    favicon: "https://alvoradafm.com.br/favicon.ico",
    tags: "pop,adult contemporary,mpb,belo horizonte",
    country: "Brazil",
    countrycode: "BR",
    state: "Minas Gerais",
    language: "portuguese",
    votes: 3120,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -19.9167,
    geo_long: -43.9345,
  },

  // --- BAHIA (SALVADOR) ---
  {
    changeuuid: "br-ba-piata",
    stationuuid: "br-ba-piata",
    name: "Piatã FM 94.3 Salvador",
    url: "https://stream.zeno.fm/u1x4zpywv0hvv",
    url_resolved: "https://stream.zeno.fm/u1x4zpywv0hvv",
    homepage: "https://piatafm.com.br",
    favicon: "https://piatafm.com.br/favicon.ico",
    tags: "pagode,samba,axé,bahia,salvador",
    country: "Brazil",
    countrycode: "BR",
    state: "Bahia",
    language: "portuguese",
    votes: 3410,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -12.9777,
    geo_long: -38.5016,
  },
  {
    changeuuid: "br-ba-sociedade",
    stationuuid: "br-ba-sociedade",
    name: "Rádio Sociedade da Bahia 102.5 FM",
    url: "https://stream.zeno.fm/k2uv4tywv0hvv",
    url_resolved: "https://stream.zeno.fm/k2uv4tywv0hvv",
    homepage: "https://sociedadedabahia.com.br",
    favicon: "",
    tags: "notícias,esportes,cultura,bahia,salvador",
    country: "Brazil",
    countrycode: "BR",
    state: "Bahia",
    language: "portuguese",
    votes: 2890,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -12.9777,
    geo_long: -38.5016,
  },

  // --- DISTRITO FEDERAL (BRASÍLIA) ---
  {
    changeuuid: "br-df-senado",
    stationuuid: "br-df-senado",
    name: "Rádio Senado 91.7 FM",
    url: "https://stream.senado.leg.br/radiosenado",
    url_resolved: "https://stream.senado.leg.br/radiosenado",
    homepage: "https://www12.senado.leg.br/radio",
    favicon: "",
    tags: "mpb,jazz,notícias,cidadania,brasília",
    country: "Brazil",
    countrycode: "BR",
    state: "Distrito Federal",
    language: "portuguese",
    votes: 3100,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -15.7975,
    geo_long: -47.8919,
  },
  {
    changeuuid: "br-df-nacional",
    stationuuid: "br-df-nacional",
    name: "Rádio Nacional de Brasília 980 AM",
    url: "https://stream.ebc.com.br/radios/nacional_am",
    url_resolved: "https://stream.ebc.com.br/radios/nacional_am",
    homepage: "https://radios.ebc.com.br",
    favicon: "",
    tags: "cultura,brasilidades,notícias,ebc,brasília",
    country: "Brazil",
    countrycode: "BR",
    state: "Distrito Federal",
    language: "portuguese",
    votes: 2790,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -15.7975,
    geo_long: -47.8919,
  },

  // --- RIO GRANDE DO SUL (PORTO ALEGRE) ---
  {
    changeuuid: "br-rs-gaucha",
    stationuuid: "br-rs-gaucha",
    name: "Rádio Gaúcha 93.7 FM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/GAUCHAAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/GAUCHAAAC.aac",
    homepage: "https://gauchazh.clicrbs.com.br/radio-gaucha",
    favicon: "",
    tags: "notícias,futebol,gre-nal,porto alegre,rio grande do sul",
    country: "Brazil",
    countrycode: "BR",
    state: "Rio Grande do Sul",
    language: "portuguese",
    votes: 3950,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -30.0346,
    geo_long: -51.2177,
  },
  {
    changeuuid: "br-rs-atlantida",
    stationuuid: "br-rs-atlantida",
    name: "Atlântida FM 94.3 POA",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/ATLANTIDA_POAAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/ATLANTIDA_POAAAC.aac",
    homepage: "https://atl.clicrbs.com.br",
    favicon: "",
    tags: "pop,rock,humor,pretinho básico,porto alegre",
    country: "Brazil",
    countrycode: "BR",
    state: "Rio Grande do Sul",
    language: "portuguese",
    votes: 3410,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -30.0346,
    geo_long: -51.2177,
  },

  // --- PARANÁ (CURITIBA) ---
  {
    changeuuid: "br-pr-91rock",
    stationuuid: "br-pr-91rock",
    name: "91 Rock Curitiba 91.3 FM",
    url: "https://stream.zeno.fm/4e1v5xywv0hvv",
    url_resolved: "https://stream.zeno.fm/4e1v5xywv0hvv",
    homepage: "https://91rock.com.br",
    favicon: "",
    tags: "rock,classic rock,curitiba,paraná",
    country: "Brazil",
    countrycode: "BR",
    state: "Paraná",
    language: "portuguese",
    votes: 2850,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -25.4284,
    geo_long: -49.2733,
  },

  // --- PERNAMBUCO (RECIFE) ---
  {
    changeuuid: "br-pe-jornal",
    stationuuid: "br-pe-jornal",
    name: "Rádio Jornal Recife 90.3 FM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOJORNALAAC.aac",
    url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOJORNALAAC.aac",
    homepage: "https://radiojornal.ne10.uol.com.br",
    favicon: "",
    tags: "notícias,futebol,frevo,forró,recife,pernambuco",
    country: "Brazil",
    countrycode: "BR",
    state: "Pernambuco",
    language: "portuguese",
    votes: 2990,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -8.0476,
    geo_long: -34.877,
  },

  // --- CEARÁ (FORTALEZA) ---
  {
    changeuuid: "br-ce-jangadeiro",
    stationuuid: "br-ce-jangadeiro",
    name: "Jangadeiro FM 88.9 Fortaleza",
    url: "https://stream.zeno.fm/6y2v5xawv0hvv",
    url_resolved: "https://stream.zeno.fm/6y2v5xawv0hvv",
    homepage: "https://jangadeiro.com.br",
    favicon: "",
    tags: "forró,pop,popular,fortaleza,ceará",
    country: "Brazil",
    countrycode: "BR",
    state: "Ceará",
    language: "portuguese",
    votes: 2810,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -3.7319,
    geo_long: -38.5267,
  },

  // --- GOIÁS (GOIÂNIA) ---
  {
    changeuuid: "br-go-ouvirdeus",
    stationuuid: "br-go-ouvirdeus",
    name: "Rádio Aliança Gospel 90.9 FM",
    url: "https://stream.zeno.fm/y3np9bsrnq8uv",
    url_resolved: "https://stream.zeno.fm/y3np9bsrnq8uv",
    homepage: "https://radioaliancagospel.com.br",
    favicon: "",
    tags: "gospel,sertanejo cristão,evangelico,goiânia,goiás",
    country: "Brazil",
    countrycode: "BR",
    state: "Goiás",
    language: "portuguese",
    votes: 3210,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -16.6869,
    geo_long: -49.2648,
  },
  {
    changeuuid: "br-go-jovempangoiania",
    stationuuid: "br-go-jovempangoiania",
    name: "Jovem Pan FM 95.1 Goiânia",
    url: "https://stream.zeno.fm/g6e5t8yev0hvv",
    url_resolved: "https://stream.zeno.fm/g6e5t8yev0hvv",
    homepage: "https://jovempan.com.br",
    favicon: "https://jovempan.com.br/favicon.ico",
    tags: "pop,dance,hits,jovem pan,goiânia,goiás",
    country: "Brazil",
    countrycode: "BR",
    state: "Goiás",
    language: "portuguese",
    votes: 2980,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -16.6869,
    geo_long: -49.2648,
  },
  {
    changeuuid: "br-go-mix100",
    stationuuid: "br-go-mix100",
    name: "Mix FM Goiânia 100.9",
    url: "https://stream.zeno.fm/r8fw72ytfmhvv",
    url_resolved: "https://stream.zeno.fm/r8fw72ytfmhvv",
    homepage: "https://mixgoiania.com.br",
    favicon: "",
    tags: "pop,mpb,sertanejo,goiânia,goiás",
    country: "Brazil",
    countrycode: "BR",
    state: "Goiás",
    language: "portuguese",
    votes: 2740,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -16.6869,
    geo_long: -49.2648,
  },
  {
    changeuuid: "br-go-sertaneja",
    stationuuid: "br-go-sertaneja",
    name: "Rádio Sertaneja 104.7 FM",
    url: "https://stream.zeno.fm/v6pqb3ywv0hvv",
    url_resolved: "https://stream.zeno.fm/v6pqb3ywv0hvv",
    homepage: "https://radiosertaneja.com.br",
    favicon: "",
    tags: "sertanejo,sertanejo universitário,country brasileiro,goiânia",
    country: "Brazil",
    countrycode: "BR",
    state: "Goiás",
    language: "portuguese",
    votes: 3450,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -16.6869,
    geo_long: -49.2648,
  },
  {
    changeuuid: "br-go-executivafm",
    stationuuid: "br-go-executivafm",
    name: "Executiva FM 107.1 Goiânia",
    url: "https://stream.zeno.fm/3r5tzvywv0hvv",
    url_resolved: "https://stream.zeno.fm/3r5tzvywv0hvv",
    homepage: "https://executivafm.com.br",
    favicon: "",
    tags: "pop,rock,goiânia,adult contemporary,goiás",
    country: "Brazil",
    countrycode: "BR",
    state: "Goiás",
    language: "portuguese",
    votes: 2610,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -16.6869,
    geo_long: -49.2648,
  },
  {
    changeuuid: "br-go-sbt-radio",
    stationuuid: "br-go-sbt-radio",
    name: "Rádio SBT Goiânia 1060 AM",
    url: "https://stream.zeno.fm/0r0xa792kwzuv",
    url_resolved: "https://stream.zeno.fm/0r0xa792kwzuv",
    homepage: "https://sbt.com.br",
    favicon: "",
    tags: "notícias,variedades,esportes,goiânia,goiás",
    country: "Brazil",
    countrycode: "BR",
    state: "Goiás",
    language: "portuguese",
    votes: 2390,
    codec: "MP3",
    bitrate: 96,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -16.6869,
    geo_long: -49.2648,
  },

  // --- AMAZONAS (MANAUS) ---
  {
    changeuuid: "br-am-difusora",
    stationuuid: "br-am-difusora",
    name: "Rádio Difusora AM 580 Manaus",
    url: "https://stream.zeno.fm/0t1fkr0b0shvv",
    url_resolved: "https://stream.zeno.fm/0t1fkr0b0shvv",
    homepage: "https://rdifusora.com.br",
    favicon: "",
    tags: "notícias,regional,amazonas,manaus,cultura",
    country: "Brazil",
    countrycode: "BR",
    state: "Amazonas",
    language: "portuguese",
    votes: 2500,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -3.119,
    geo_long: -60.0217,
  },
  {
    changeuuid: "br-am-cultura-am",
    stationuuid: "br-am-cultura-am",
    name: "Cultura FM 92.3 Manaus",
    url: "https://stream.zeno.fm/s3v2ebhv0hvv",
    url_resolved: "https://stream.zeno.fm/s3v2ebhv0hvv",
    homepage: "https://culturafm.am.gov.br",
    favicon: "",
    tags: "cultura,amazônia,regional,manaus,folclore",
    country: "Brazil",
    countrycode: "BR",
    state: "Amazonas",
    language: "portuguese",
    votes: 2280,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -3.119,
    geo_long: -60.0217,
  },

  // --- SANTA CATARINA (FLORIANÓPOLIS) ---
  {
    changeuuid: "br-sc-floripa-fm",
    stationuuid: "br-sc-floripa-fm",
    name: "Floripa FM 103.1",
    url: "https://stream.zeno.fm/5n3f7yywv0hvv",
    url_resolved: "https://stream.zeno.fm/5n3f7yywv0hvv",
    homepage: "https://floripafm.com.br",
    favicon: "",
    tags: "pop,indie,surf,florianópolis,santa catarina",
    country: "Brazil",
    countrycode: "BR",
    state: "Santa Catarina",
    language: "portuguese",
    votes: 2680,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -27.5954,
    geo_long: -48.548,
  },
  {
    changeuuid: "br-sc-itapoa",
    stationuuid: "br-sc-itapoa",
    name: "Rádio Itapoá FM 99.5 SC",
    url: "https://stream.zeno.fm/a9x2e3ywv0hvv",
    url_resolved: "https://stream.zeno.fm/a9x2e3ywv0hvv",
    homepage: "https://itapoafm.com.br",
    favicon: "",
    tags: "eletrônica,dance,pop,santa catarina,florianópolis",
    country: "Brazil",
    countrycode: "BR",
    state: "Santa Catarina",
    language: "portuguese",
    votes: 2450,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -27.5954,
    geo_long: -48.548,
  },
];
