import { City } from "./types";

export const WORLD_CITIES: City[] = [
  {
    name: "Paris",
    country: "France",
    countryCode: "FR",
    lat: 48.8566,
    lng: 2.3522,
    stationCount: 112,
    tagline: "The capital of eclectic waves, jazz and bohemian frequencies.",
    primaryTag: "jazz,eclectic",
  },
  {
    name: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    lat: 35.6762,
    lng: 139.6503,
    stationCount: 94,
    tagline: "Neon-drenched city pop, ambient synthesis and Shibuya soundscapes.",
    primaryTag: "jpop,ambient",
  },
  {
    name: "São Paulo",
    country: "Brazil",
    countryCode: "BR",
    lat: -23.5505,
    lng: -46.6333,
    stationCount: 143,
    tagline: "Pulsing metropolis of MPB, samba rock, electronic and urban beats.",
    primaryTag: "mpb,brazil,samba",
  },
  {
    name: "Rio de Janeiro",
    country: "Brazil",
    countryCode: "BR",
    lat: -22.9068,
    lng: -43.1729,
    stationCount: 88,
    tagline: "Bossa nova breezes, coastal rhythms and tropical frequencies.",
    primaryTag: "bossa nova,mpb",
  },
  {
    name: "London",
    country: "United Kingdom",
    countryCode: "GB",
    lat: 51.5074,
    lng: -0.1278,
    stationCount: 135,
    tagline: "Pirate radio heritage, grime, UK bass and cutting-edge indie.",
    primaryTag: "indie,electronic",
  },
  {
    name: "New York",
    country: "United States",
    countryCode: "US",
    lat: 40.7128,
    lng: -74.006,
    stationCount: 160,
    tagline: "East Coast hip-hop origins, loft jazz and timeless broadcaster towers.",
    primaryTag: "hiphop,jazz,talk",
  },
  {
    name: "Berlin",
    country: "Germany",
    countryCode: "DE",
    lat: 52.52,
    lng: 13.405,
    stationCount: 104,
    tagline: "Minimal techno sanctuaries, industrial resonance and avant-garde art.",
    primaryTag: "techno,electronic",
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    lat: 52.3676,
    lng: 4.9041,
    stationCount: 76,
    tagline: "Canalside house grooves, chillout lounges and global dance music.",
    primaryTag: "dance,house",
  },
  {
    name: "Seoul",
    country: "South Korea",
    countryCode: "KR",
    lat: 37.5665,
    lng: 126.978,
    stationCount: 68,
    tagline: "Futuristic synth-pop, K-rhythms and late-night Han River ballads.",
    primaryTag: "kpop,pop",
  },
  {
    name: "Bangkok",
    country: "Thailand",
    countryCode: "TH",
    lat: 13.7563,
    lng: 100.5018,
    stationCount: 52,
    tagline: "Siam psychedelic funk, night bazaar melodies and tropical warmth.",
    primaryTag: "thai,chill",
  },
  {
    name: "Cape Town",
    country: "South Africa",
    countryCode: "ZA",
    lat: -33.9249,
    lng: 18.4241,
    stationCount: 45,
    tagline: "Amapiano vibrations, deep Afro-house and coastal jazz.",
    primaryTag: "amapiano,house",
  },
  {
    name: "Sydney",
    country: "Australia",
    countryCode: "AU",
    lat: -33.8688,
    lng: 151.2093,
    stationCount: 72,
    tagline: "Pacific indie waves, sun-soaked rock and community airwaves.",
    primaryTag: "indie,rock",
  },
  {
    name: "Montreal",
    country: "Canada",
    countryCode: "CA",
    lat: 45.5017,
    lng: -73.5673,
    stationCount: 63,
    tagline: "Bilingual indie rock, underground techno and historic jazz clubs.",
    primaryTag: "french,indie",
  },
  {
    name: "Barcelona",
    country: "Spain",
    countryCode: "ES",
    lat: 41.3879,
    lng: 2.1699,
    stationCount: 81,
    tagline: "Mediterranean balearic sunsets, flamenco modernism and club sound.",
    primaryTag: "spanish,electronic",
  },
  {
    name: "Rome",
    country: "Italy",
    countryCode: "IT",
    lat: 41.9028,
    lng: 12.4964,
    stationCount: 89,
    tagline: "Cinematic soundtracks, classic Italian pop and evening jazz.",
    primaryTag: "italian,pop,classic",
  },
  {
    name: "Reykjavík",
    country: "Iceland",
    countryCode: "IS",
    lat: 64.1466,
    lng: -21.9426,
    stationCount: 32,
    tagline: "Glacial ambient, ethereal post-rock and volcanic audio textures.",
    primaryTag: "ambient,indie",
  },
  {
    name: "Buenos Aires",
    country: "Argentina",
    countryCode: "AR",
    lat: -34.6037,
    lng: -58.3816,
    stationCount: 118,
    tagline: "Passionate tango nostalgia, Argentine rock and late-night bohemia.",
    primaryTag: "rock,tango,latin",
  },
  {
    name: "Mexico City",
    country: "Mexico",
    countryCode: "MX",
    lat: 19.4326,
    lng: -99.1332,
    stationCount: 105,
    tagline: "Cumbia sonidera, vibrant mariachi and alternative Latin beats.",
    primaryTag: "latin,cumbia,rock",
  },
  {
    name: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    lat: 38.7223,
    lng: -9.1393,
    stationCount: 78,
    tagline: "Melancholic fado alleys, Batida rhythms and Atlantic breezes.",
    primaryTag: "fado,portuguese",
  },
  {
    name: "Kingston",
    country: "Jamaica",
    countryCode: "JM",
    lat: 18.0179,
    lng: -76.8099,
    stationCount: 39,
    tagline: "The birthplace of reggae, dub sound systems and dancehall energy.",
    primaryTag: "reggae,dub,dancehall",
  },
  {
    name: "Lagos",
    country: "Nigeria",
    countryCode: "NG",
    lat: 6.5244,
    lng: 3.3792,
    stationCount: 56,
    tagline: "Afrobeats epicenter, highlife royalty and relentless rhythmic drive.",
    primaryTag: "afrobeats,african",
  },
  {
    name: "San Francisco",
    country: "United States",
    countryCode: "US",
    lat: 37.7749,
    lng: -122.4194,
    stationCount: 95,
    tagline: "Psychedelic heritage, ambient chillout and Bay Area hip-hop.",
    primaryTag: "ambient,rock,indie",
  },
  {
    name: "Havana",
    country: "Cuba",
    countryCode: "CU",
    lat: 23.1136,
    lng: -82.3666,
    stationCount: 28,
    tagline: "Son cubano, Buena Vista acoustic brass and afro-cuban percussion.",
    primaryTag: "cuban,latin,salsa",
  },
  {
    name: "Salvador",
    country: "Brazil",
    countryCode: "BR",
    lat: -12.9777,
    lng: -38.5016,
    stationCount: 65,
    tagline: "Axé ancestral drumming, samba-reggae and golden tropical coasts.",
    primaryTag: "axe,samba,brazil",
  },
  {
    name: "Istanbul",
    country: "Turkey",
    countryCode: "TR",
    lat: 41.0082,
    lng: 28.9784,
    stationCount: 84,
    tagline: "Bosphorus acoustic crossroads, Anatolian rock and mystic Sufi flutes.",
    primaryTag: "turkish,oriental",
  },
  {
    name: "Vienna",
    country: "Austria",
    countryCode: "AT",
    lat: 48.2082,
    lng: 16.3738,
    stationCount: 61,
    tagline: "Classical orchestra halls, imperial waltzes and downtempo dub.",
    primaryTag: "classical,downtempo",
  },
  {
    name: "Belo Horizonte",
    country: "Brazil",
    countryCode: "BR",
    lat: -19.9167,
    lng: -43.9345,
    stationCount: 78,
    tagline: "Clube da Esquina, pop rock mineiro e tradição radialista.",
    primaryTag: "mpb,rock,notícias",
  },
  {
    name: "Brasília",
    country: "Brazil",
    countryCode: "BR",
    lat: -15.7975,
    lng: -47.8919,
    stationCount: 72,
    tagline: "Berço do rock nacional dos anos 80, cidadania e ondas públicas.",
    primaryTag: "rock,notícias,cultura",
  },
  {
    name: "Porto Alegre",
    country: "Brazil",
    countryCode: "BR",
    lat: -30.0346,
    lng: -51.2177,
    stationCount: 84,
    tagline: "Rock gaúcho, cultura pampeana, esportes fervorosos e debates.",
    primaryTag: "rock,notícias,esportes",
  },
  {
    name: "Curitiba",
    country: "Brazil",
    countryCode: "BR",
    lat: -25.4284,
    lng: -49.2733,
    stationCount: 69,
    tagline: "Cena alternativa vibrante, classic rock e parques sonoros.",
    primaryTag: "rock,indie,pop",
  },
  {
    name: "Recife",
    country: "Brazil",
    countryCode: "BR",
    lat: -8.0476,
    lng: -34.877,
    stationCount: 66,
    tagline: "Frevo elétrico, manguebeat revolucionário, maracatu e forró.",
    primaryTag: "frevo,manguebeat,forro",
  },
  {
    name: "Fortaleza",
    country: "Brazil",
    countryCode: "BR",
    lat: -3.7319,
    lng: -38.5267,
    stationCount: 58,
    tagline: "Ritmos litorâneos cearenses, forró eletrônico e cultura viva.",
    primaryTag: "forro,pop,popular",
  },
  {
    name: "Goiânia",
    country: "Brazil",
    countryCode: "BR",
    lat: -16.6869,
    lng: -49.2648,
    stationCount: 54,
    tagline: "Epicentro sertanejo do cerrado e festivais de indie rock.",
    primaryTag: "sertanejo,rock,pop",
  },
  {
    name: "Manaus",
    country: "Brazil",
    countryCode: "BR",
    lat: -3.119,
    lng: -60.0217,
    stationCount: 42,
    tagline: "Toadas do boi-bumbá, carimbó, eco-frequências e beiradão.",
    primaryTag: "amazonas,regional,cultura",
  },
  {
    name: "Florianópolis",
    country: "Brazil",
    countryCode: "BR",
    lat: -27.5954,
    lng: -48.548,
    stationCount: 48,
    tagline: "Ilha do Silício e da magia: surf music, eletrônica e praias.",
    primaryTag: "surf,electronic,reggae",
  },

];
