import { Station } from "./types";

export const SPOTLIGHT_STATIONS: Station[] = [
  {
    changeuuid: "fip-paris-01",
    stationuuid: "fip-paris-01",
    name: "FIP",
    url: "https://icecast.radiofrance.fr/fip-midfi.mp3",
    url_resolved: "https://icecast.radiofrance.fr/fip-midfi.mp3",
    homepage: "https://www.radiofrance.fr/fip",
    favicon: "https://www.radiofrance.fr/assets/favicons/fip.png",
    tags: "eclectic,jazz,world,rock,groove",
    country: "France",
    countrycode: "FR",
    state: "Île-de-France",
    language: "french",
    votes: 4890,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 48.8566,
    geo_long: 2.3522,
  },
  {
    changeuuid: "kexp-seattle-02",
    stationuuid: "kexp-seattle-02",
    name: "KEXP 90.3 FM",
    url: "https://kexp.streamguys1.com/kexp128.mp3",
    url_resolved: "https://kexp.streamguys1.com/kexp128.mp3",
    homepage: "https://kexp.org",
    favicon: "https://kexp.org/static/assets/img/kexp-logo-square.png",
    tags: "indie,alternative,rock,curated",
    country: "United States",
    countrycode: "US",
    state: "Washington",
    language: "english",
    votes: 5210,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 47.6062,
    geo_long: -122.3321,
  },
  {
    changeuuid: "nts-london-03",
    stationuuid: "nts-london-03",
    name: "NTS Radio 1",
    url: "https://stream-relay-geo.ntslive.net/stream",
    url_resolved: "https://stream-relay-geo.ntslive.net/stream",
    homepage: "https://www.nts.live",
    favicon: "https://www.nts.live/favicon.ico",
    tags: "underground,electronic,experimental,ambient",
    country: "United Kingdom",
    countrycode: "GB",
    state: "London",
    language: "english",
    votes: 4120,
    codec: "MP3",
    bitrate: 192,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 51.5074,
    geo_long: -0.1278,
  },
  {
    changeuuid: "radio-paradise-04",
    stationuuid: "radio-paradise-04",
    name: "Radio Paradise (Main Mix)",
    url: "https://stream.radioparadise.com/mp3-192",
    url_resolved: "https://stream.radioparadise.com/mp3-192",
    homepage: "https://radioparadise.com",
    favicon: "https://radioparadise.com/favicon.ico",
    tags: "eclectic,mellow,acoustic,indie",
    country: "United States",
    countrycode: "US",
    state: "California",
    language: "english",
    votes: 3950,
    codec: "MP3",
    bitrate: 192,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 39.7596,
    geo_long: -121.6219,
  },
  {
    changeuuid: "groove-salad-05",
    stationuuid: "groove-salad-05",
    name: "SomaFM Groove Salad",
    url: "https://ice2.somafm.com/groovesalad-128-mp3",
    url_resolved: "https://ice2.somafm.com/groovesalad-128-mp3",
    homepage: "https://somafm.com/groovesalad/",
    favicon: "https://somafm.com/img3/groovesalad120.png",
    tags: "downtempo,chillout,ambient,lounge",
    country: "United States",
    countrycode: "US",
    state: "San Francisco",
    language: "english",
    votes: 3740,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 37.7749,
    geo_long: -122.4194,
  },
  {
    changeuuid: "alpha-fm-sp-06",
    stationuuid: "alpha-fm-sp-06",
    name: "Alpha FM 101.7",
    url: "https://26683.live.streamtheworld.com/RADIO_ALPHAFMAAC.aac",
    url_resolved: "https://26683.live.streamtheworld.com/RADIO_ALPHAFMAAC.aac",
    homepage: "https://www.alphapm.com.br",
    favicon: "https://www.alphapm.com.br/favicon.ico",
    tags: "mpb,pop,adult contemporary,brazil",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3600,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
];

export const FALLBACK_CITY_STATIONS: Record<string, Station[]> = {
  Paris: [
    SPOTLIGHT_STATIONS[0],
    {
      changeuuid: "tsf-jazz-paris",
      stationuuid: "tsf-jazz-paris",
      name: "TSF Jazz 89.9",
      url: "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
      url_resolved: "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
      homepage: "https://www.tsfjazz.com",
      favicon: "https://www.tsfjazz.com/favicon.ico",
      tags: "jazz,swing,blues",
      country: "France",
      countrycode: "FR",
      state: "Paris",
      language: "french",
      votes: 1840,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "fip-rock-paris",
      stationuuid: "fip-rock-paris",
      name: "FIP Rock",
      url: "https://icecast.radiofrance.fr/fiprock-midfi.mp3",
      url_resolved: "https://icecast.radiofrance.fr/fiprock-midfi.mp3",
      homepage: "https://www.radiofrance.fr/fip",
      favicon: "https://www.radiofrance.fr/assets/favicons/fip.png",
      tags: "rock,indie,alternative",
      country: "France",
      countrycode: "FR",
      state: "Paris",
      language: "french",
      votes: 2190,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  Tokyo: [
    {
      changeuuid: "jpop-sakura-tokyo",
      stationuuid: "jpop-sakura-tokyo",
      name: "J-Pop Sakura 懐かしい",
      url: "https://kathy.torontocast.com:3560/stream",
      url_resolved: "https://kathy.torontocast.com:3560/stream",
      homepage: "https://japanimradio.com",
      favicon: "",
      tags: "jpop,anime,tokyo,japan",
      country: "Japan",
      countrycode: "JP",
      state: "Tokyo",
      language: "japanese",
      votes: 2410,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "asia-dream-japan",
      stationuuid: "asia-dream-japan",
      name: "Asia DREAM Radio - Japan",
      url: "https://cast1.torontocast.com:2160/stream",
      url_resolved: "https://cast1.torontocast.com:2160/stream",
      homepage: "https://asiadreamradio.com",
      favicon: "",
      tags: "jpop,hits,ballads,tokyo",
      country: "Japan",
      countrycode: "JP",
      state: "Tokyo",
      language: "japanese",
      votes: 1920,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  "São Paulo": [
    SPOTLIGHT_STATIONS[5],
    {
      changeuuid: "antena-um-sp",
      stationuuid: "antena-um-sp",
      name: "Antena 1 94.7 FM",
      url: "https://antenaone.crossradio.com.br/stream/1",
      url_resolved: "https://antenaone.crossradio.com.br/stream/1",
      homepage: "https://www.antena1.com.br",
      favicon: "https://www.antena1.com.br/favicon.ico",
      tags: "pop,classic pop,adult contemporary,hits",
      country: "Brazil",
      countrycode: "BR",
      state: "São Paulo",
      language: "portuguese",
      votes: 3120,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "radio-rock-sp",
      stationuuid: "radio-rock-sp",
      name: "89 FM A Rádio Rock",
      url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_89FM_ADP.aac?dist=site-89fm",
      url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_89FM_ADP.aac?dist=site-89fm",
      homepage: "https://www.radiorock.com.br",
      favicon: "https://www.radiorock.com.br/favicon.ico",
      tags: "rock,classic rock,alternative,indie",
      country: "Brazil",
      countrycode: "BR",
      state: "São Paulo",
      language: "portuguese",
      votes: 3890,
      codec: "AAC",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  London: [
    SPOTLIGHT_STATIONS[2],
    {
      changeuuid: "bbc-radio-6",
      stationuuid: "bbc-radio-6",
      name: "BBC Radio 6 Music",
      url: "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
      url_resolved: "https://stream.live.vc.bbcmedia.co.uk/bbc_6music",
      homepage: "https://www.bbc.co.uk/6music",
      favicon: "https://www.bbc.co.uk/favicon.ico",
      tags: "alternative,indie,rock,electronic",
      country: "United Kingdom",
      countrycode: "GB",
      state: "London",
      language: "english",
      votes: 4950,
      codec: "AAC",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  Berlin: [
    {
      changeuuid: "hirschmilch-electronic",
      stationuuid: "hirschmilch-electronic",
      name: "Hirschmilch Chillout",
      url: "https://hirschmilch.de:7001/chillout.mp3",
      url_resolved: "https://hirschmilch.de:7001/chillout.mp3",
      homepage: "https://hirschmilch.de",
      favicon: "",
      tags: "chillout,ambient,psybient,electronic",
      country: "Germany",
      countrycode: "DE",
      state: "Berlin",
      language: "german",
      votes: 1540,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "fip-jazz-stream",
      stationuuid: "fip-jazz-stream",
      name: "FIP Jazz",
      url: "https://icecast.radiofrance.fr/fipjazz-midfi.mp3",
      url_resolved: "https://icecast.radiofrance.fr/fipjazz-midfi.mp3",
      homepage: "https://www.radiofrance.fr/fip",
      favicon: "https://www.radiofrance.fr/assets/favicons/fip.png",
      tags: "jazz,vocal,berlin,world",
      country: "Germany",
      countrycode: "DE",
      state: "Berlin",
      language: "german",
      votes: 1890,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  "Rio de Janeiro": [
    {
      changeuuid: "jb-fm-rio",
      stationuuid: "jb-fm-rio",
      name: "JB FM 99.9",
      url: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
      url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
      homepage: "https://jb.fm",
      favicon: "https://jb.fm/favicon.ico",
      tags: "mpb,bossa nova,pop,rio",
      country: "Brazil",
      countrycode: "BR",
      state: "Rio de Janeiro",
      language: "portuguese",
      votes: 2840,
      codec: "AAC",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "bossa-jazz-brasil",
      stationuuid: "bossa-jazz-brasil",
      name: "Bossa Jazz Brasil",
      url: "https://centova5.transmissaodigital.com:20104/live",
      url_resolved: "https://centova5.transmissaodigital.com:20104/live",
      homepage: "https://bossajazzbrasil.com",
      favicon: "",
      tags: "bossa nova,samba jazz,mpb",
      country: "Brazil",
      countrycode: "BR",
      state: "Rio de Janeiro",
      language: "portuguese",
      votes: 1930,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "super-radio-tupi",
      stationuuid: "super-radio-tupi",
      name: "Super Rádio Tupi 96.5 FM",
      url: "https://8923.brasilstream.com.br/stream",
      url_resolved: "https://8923.brasilstream.com.br/stream",
      homepage: "https://tupi.fm",
      favicon: "",
      tags: "notícias,esportes,variedades,rio",
      country: "Brazil",
      countrycode: "BR",
      state: "Rio de Janeiro",
      language: "portuguese",
      votes: 3120,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
};
