import { Station } from "./types";

export const SPOTLIGHT_STATIONS: Station[] = [
  {
    changeuuid: "fip-paris-01",
    stationuuid: "fip-paris-01",
    name: "FIP",
    url: "https://icecast.radiofrance.fr/fip-midfi.mp3",
    url_resolved: "https://icecast.radiofrance.fr/fip-midfi.mp3",
    homepage: "https://www.radiofrance.fr/fip",
    favicon: "https://www.radiofrance.fr/assets/favicons/fip.png",
    tags: "eclectic,jazz,world,rock,groove",
    country: "France",
    countrycode: "FR",
    state: "Île-de-France",
    language: "french",
    votes: 4890,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 48.8566,
    geo_long: 2.3522,
  },
  {
    changeuuid: "kexp-seattle-02",
    stationuuid: "kexp-seattle-02",
    name: "KEXP 90.3 FM",
    url: "https://kexp.streamguys1.com/kexp128.mp3",
    url_resolved: "https://kexp.streamguys1.com/kexp128.mp3",
    homepage: "https://kexp.org",
    favicon: "https://kexp.org/static/assets/img/kexp-logo-square.png",
    tags: "indie,alternative,rock,curated",
    country: "United States",
    countrycode: "US",
    state: "Washington",
    language: "english",
    votes: 5210,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 47.6062,
    geo_long: -122.3321,
  },
  {
    changeuuid: "nts-london-03",
    stationuuid: "nts-london-03",
    name: "NTS Radio 1",
    url: "https://stream-relay-geo.ntslive.net/stream",
    url_resolved: "https://stream-relay-geo.ntslive.net/stream",
    homepage: "https://www.nts.live",
    favicon: "https://www.nts.live/favicon.ico",
    tags: "underground,electronic,experimental,ambient",
    country: "United Kingdom",
    countrycode: "GB",
    state: "London",
    language: "english",
    votes: 4120,
    codec: "MP3",
    bitrate: 192,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 51.5074,
    geo_long: -0.1278,
  },
  {
    changeuuid: "radio-paradise-04",
    stationuuid: "radio-paradise-04",
    name: "Radio Paradise (Main Mix)",
    url: "https://stream.radioparadise.com/mp3-192",
    url_resolved: "https://stream.radioparadise.com/mp3-192",
    homepage: "https://radioparadise.com",
    favicon: "https://radioparadise.com/favicon.ico",
    tags: "eclectic,mellow,acoustic,indie",
    country: "United States",
    countrycode: "US",
    state: "California",
    language: "english",
    votes: 3950,
    codec: "MP3",
    bitrate: 192,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 39.7596,
    geo_long: -121.6219,
  },
  {
    changeuuid: "groove-salad-05",
    stationuuid: "groove-salad-05",
    name: "SomaFM Groove Salad",
    url: "https://ice2.somafm.com/groovesalad-128-mp3",
    url_resolved: "https://ice2.somafm.com/groovesalad-128-mp3",
    homepage: "https://somafm.com/groovesalad/",
    favicon: "https://somafm.com/img3/groovesalad120.png",
    tags: "downtempo,chillout,ambient,lounge",
    country: "United States",
    countrycode: "US",
    state: "San Francisco",
    language: "english",
    votes: 3740,
    codec: "MP3",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: 37.7749,
    geo_long: -122.4194,
  },
  {
    changeuuid: "alpha-fm-sp-06",
    stationuuid: "alpha-fm-sp-06",
    name: "Alpha FM 101.7",
    url: "https://26683.live.streamtheworld.com/RADIO_ALPHAFMAAC.aac",
    url_resolved: "https://26683.live.streamtheworld.com/RADIO_ALPHAFMAAC.aac",
    homepage: "https://www.alphapm.com.br",
    favicon: "https://www.alphapm.com.br/favicon.ico",
    tags: "mpb,pop,adult contemporary,brazil",
    country: "Brazil",
    countrycode: "BR",
    state: "São Paulo",
    language: "portuguese",
    votes: 3600,
    codec: "AAC",
    bitrate: 128,
    hls: 0,
    lastcheckok: 1,
    geo_lat: -23.5505,
    geo_long: -46.6333,
  },
];

export const FALLBACK_CITY_STATIONS: Record<string, Station[]> = {
  Paris: [
    SPOTLIGHT_STATIONS[0],
    {
      changeuuid: "tsf-jazz-paris",
      stationuuid: "tsf-jazz-paris",
      name: "TSF Jazz",
      url: "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
      url_resolved: "https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
      homepage: "https://www.tsfjazz.com",
      favicon: "https://www.tsfjazz.com/favicon.ico",
      tags: "jazz,swing,blues",
      country: "France",
      countrycode: "FR",
      state: "Paris",
      language: "french",
      votes: 1840,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "nova-paris",
      stationuuid: "nova-paris",
      name: "Radio Nova",
      url: "https://radionova.ice.infomaniak.ch/radionova-high.mp3",
      url_resolved: "https://radionova.ice.infomaniak.ch/radionova-high.mp3",
      homepage: "https://www.nova.fr",
      favicon: "https://www.nova.fr/favicon.ico",
      tags: "groove,funk,world,hiphop",
      country: "France",
      countrycode: "FR",
      state: "Paris",
      language: "french",
      votes: 2190,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  Tokyo: [
    {
      changeuuid: "jpop-sakura-tokyo",
      stationuuid: "jpop-sakura-tokyo",
      name: "J-Pop Sakura 懐かしい",
      url: "https://kathy.torontocast.com:3560/stream",
      url_resolved: "https://kathy.torontocast.com:3560/stream",
      homepage: "https://japanimradio.com",
      favicon: "",
      tags: "jpop,anime,tokyo,japan",
      country: "Japan",
      countrycode: "JP",
      state: "Tokyo",
      language: "japanese",
      votes: 2410,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "asia-dream-japan",
      stationuuid: "asia-dream-japan",
      name: "Asia DREAM Radio - Japan",
      url: "https://cast1.torontocast.com:2160/stream",
      url_resolved: "https://cast1.torontocast.com:2160/stream",
      homepage: "https://asiadreamradio.com",
      favicon: "",
      tags: "jpop,hits,ballads,tokyo",
      country: "Japan",
      countrycode: "JP",
      state: "Tokyo",
      language: "japanese",
      votes: 1920,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  "São Paulo": [
    SPOTLIGHT_STATIONS[5],
    {
      changeuuid: "antena-um-sp",
      stationuuid: "antena-um-sp",
      name: "Antena 1 94.7 FM",
      url: "https://antenaone.crossradio.com.br/stream/1",
      url_resolved: "https://antenaone.crossradio.com.br/stream/1",
      homepage: "https://www.antena1.com.br",
      favicon: "https://www.antena1.com.br/favicon.ico",
      tags: "pop,classic pop,adult contemporary,hits",
      country: "Brazil",
      countrycode: "BR",
      state: "São Paulo",
      language: "portuguese",
      votes: 3120,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "cultura-brasil-sp",
      stationuuid: "cultura-brasil-sp",
      name: "Rádio Cultura Brasil 1200 AM",
      url: "https://stream.zeno.fm/g4f4v6y2vahvv",
      url_resolved: "https://stream.zeno.fm/g4f4v6y2vahvv",
      homepage: "https://culturabrasil.cmais.com.br",
      favicon: "",
      tags: "mpb,choro,samba,cultura",
      country: "Brazil",
      countrycode: "BR",
      state: "São Paulo",
      language: "portuguese",
      votes: 1680,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  London: [
    SPOTLIGHT_STATIONS[2],
    {
      changeuuid: "worldwide-fm-london",
      stationuuid: "worldwide-fm-london",
      name: "Worldwide FM",
      url: "https://worldwidefm.out.airtime.pro/worldwidefm_b",
      url_resolved: "https://worldwidefm.out.airtime.pro/worldwidefm_b",
      homepage: "https://worldwidefm.net",
      favicon: "https://worldwidefm.net/favicon.ico",
      tags: "global beats,jazz,afro,eclectic",
      country: "United Kingdom",
      countrycode: "GB",
      state: "London",
      language: "english",
      votes: 2790,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "rinse-fm-london",
      stationuuid: "rinse-fm-london",
      name: "Rinse FM",
      url: "https://streamer-duo.rinse.fm/rinseradio",
      url_resolved: "https://streamer-duo.rinse.fm/rinseradio",
      homepage: "https://rinse.fm",
      favicon: "https://rinse.fm/favicon.ico",
      tags: "grime,garage,bass,electronic",
      country: "United Kingdom",
      countrycode: "GB",
      state: "London",
      language: "english",
      votes: 1940,
      codec: "MP3",
      bitrate: 160,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  Berlin: [
    {
      changeuuid: "fluxfm-berlin",
      stationuuid: "fluxfm-berlin",
      name: "FluxFM Berlin",
      url: "https://fluxfm.streamabc.net/flx-fluxfmberlin-mp3-128-2617757",
      url_resolved: "https://fluxfm.streamabc.net/flx-fluxfmberlin-mp3-128-2617757",
      homepage: "https://www.fluxfm.de",
      favicon: "https://www.fluxfm.de/favicon.ico",
      tags: "indie,alternative,electronic,berlin",
      country: "Germany",
      countrycode: "DE",
      state: "Berlin",
      language: "german",
      votes: 2130,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "hirschmilch-electronic",
      stationuuid: "hirschmilch-electronic",
      name: "Hirschmilch Chillout",
      url: "https://hirschmilch.de:7001/chillout.mp3",
      url_resolved: "https://hirschmilch.de:7001/chillout.mp3",
      homepage: "https://hirschmilch.de",
      favicon: "",
      tags: "chillout,ambient,psybient,electronic",
      country: "Germany",
      countrycode: "DE",
      state: "Berlin",
      language: "german",
      votes: 1540,
      codec: "MP3",
      bitrate: 192,
      hls: 0,
      lastcheckok: 1,
    },
  ],
  "Rio de Janeiro": [
    {
      changeuuid: "jb-fm-rio",
      stationuuid: "jb-fm-rio",
      name: "JB FM 99.9",
      url: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
      url_resolved: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
      homepage: "https://jb.fm",
      favicon: "https://jb.fm/favicon.ico",
      tags: "mpb,bossa nova,pop,rio",
      country: "Brazil",
      countrycode: "BR",
      state: "Rio de Janeiro",
      language: "portuguese",
      votes: 2840,
      codec: "AAC",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
    {
      changeuuid: "bossa-jazz-brasil",
      stationuuid: "bossa-jazz-brasil",
      name: "Bossa Jazz Brasil",
      url: "https://ssl.painelcast.com:6956/stream",
      url_resolved: "https://ssl.painelcast.com:6956/stream",
      homepage: "https://bossajazzbrasil.com",
      favicon: "",
      tags: "bossa nova,samba jazz,mpb",
      country: "Brazil",
      countrycode: "BR",
      state: "Rio de Janeiro",
      language: "portuguese",
      votes: 1930,
      codec: "MP3",
      bitrate: 128,
      hls: 0,
      lastcheckok: 1,
    },
  ],
};
